name: CD on Push to master

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha}} .
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha}}


      - name: "Deployment"
        run: |
          echo "Deployment steps skipped."
          echo "Docker image built and pushed to Docker Hub with tag: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}"